import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Upload, ShieldCheck, Network, MessageSquare, FileText, CheckCircle2, AlertTriangle, GitBranch } from 'lucide-react'
import { getCategories, getEvaluationSummary, getSkillEvidence } from '../lib/api'

export default function Dashboard(){
  const [categories,setCategories]=useState(null),[evidence,setEvidence]=useState(null),[quality,setQuality]=useState(null),[error,setError]=useState('')
  useEffect(()=>{Promise.all([getCategories(),getSkillEvidence(),getEvaluationSummary()]).then(([c,e,q])=>{setCategories(c);setEvidence(e);setQuality(q)}).catch(err=>setError(err.message))},[])
  if(error)return <div className="card" style={{margin:32,padding:24,color:'#fca5a5'}}>{error}</div>
  const docs=categories?.documents||[]
  return <div style={{padding:'32px 36px',maxWidth:1250,margin:'0 auto'}}>
    <div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',marginBottom:26}}><div><div className="eyebrow"><ShieldCheck size={14}/> EVIDENCE-BACKED DIGITAL IDENTITY</div><h1 className="heading-display" style={{fontSize:'2.15rem',margin:'6px 0'}}>Your career journey, with proof</h1><p style={{color:'#94a3b8',maxWidth:700}}>MemoryVerse organizes original documents, connects skills to projects and internships, and answers questions with exact evidence citations.</p></div><Link to="/upload" className="btn-primary" style={{textDecoration:'none'}}><Upload size={16}/> Add evidence</Link></div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:14,marginBottom:20}}>{[
      ['Documents',categories?.total||0,FileText],['Evidenced skills',evidence?.skill_count||0,ShieldCheck],['Graph links',quality?.relationship_count||0,Network],['Needs review',docs.filter(d=>d.review_required).length,AlertTriangle]
    ].map(([label,value,Icon])=><div className="card" key={label} style={{padding:18,display:'flex',gap:12,alignItems:'center'}}><Icon size={21}/><div><b style={{fontSize:23}}>{value}</b><div style={{fontSize:12,color:'#64748b'}}>{label}</div></div></div>)}</div>
    <div style={{display:'grid',gridTemplateColumns:'1.4fr .9fr',gap:18}}><section className="card" style={{padding:22}}><div style={{display:'flex',justifyContent:'space-between'}}><h2 style={{fontSize:17,margin:0}}>Strongest skill evidence</h2><Link to="/evidence" style={{fontSize:12,color:'#60a5fa'}}>Open passport</Link></div><div style={{display:'grid',gap:12,marginTop:16}}>{(evidence?.top_skills||[]).slice(0,6).map(s=><div key={s.skill}><div style={{display:'flex',justifyContent:'space-between',fontSize:13}}><b>{s.skill}</b><span style={{color:'#22d3ee'}}>{s.evidence_level} · {s.evidence_score}</span></div><div style={{height:6,background:'#1e293b',borderRadius:8,marginTop:7}}><div style={{width:`${s.evidence_score}%`,height:'100%',background:'linear-gradient(90deg,#3b82f6,#22d3ee)',borderRadius:8}}/></div></div>)}{!evidence?.skill_count&&<p style={{color:'#64748b'}}>Upload a certificate, project, internship, or GitHub repository to build evidence.</p>}</div></section>
      <section className="card" style={{padding:22}}><h2 style={{fontSize:17,marginTop:0}}>AI quality coverage</h2>{quality&&<div style={{display:'grid',gap:13}}>{[['Readable documents',quality.readable_document_ratio],['Citation ready',quality.citation_ready_ratio],['Reviewed metadata',quality.reviewed_ratio],['Verified sources',quality.verified_ratio]].map(([label,ratio])=><div key={label}><div style={{display:'flex',justifyContent:'space-between',fontSize:12}}><span>{label}</span><b>{Math.round((ratio||0)*100)}%</b></div><div style={{height:5,background:'#1e293b',marginTop:6,borderRadius:7}}><div style={{height:'100%',width:`${(ratio||0)*100}%`,background:'#10b981',borderRadius:7}}/></div></div>)}</div>}<p style={{fontSize:11,color:'#64748b',marginTop:16}}>Coverage metrics are shown instead of fabricated model-accuracy or job-success claims.</p></section></div>
    <section className="card" style={{padding:22,marginTop:18}}><h2 style={{fontSize:17,marginTop:0}}>Winning demo flow</h2><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12}}>{[[Upload,'1. Ingest','Upload documents'],[GitBranch,'2. Link','Import GitHub evidence'],[Network,'3. Connect','Inspect evidence graph'],[MessageSquare,'4. Prove','Ask with citations']].map(([Icon,title,text])=><div key={title} style={{padding:14,background:'rgba(15,23,42,.55)',borderRadius:11}}><Icon size={19}/><b style={{display:'block',margin:'8px 0 3px'}}>{title}</b><span style={{fontSize:12,color:'#64748b'}}>{text}</span></div>)}</div></section>
  </div>
}
