import { useState } from 'react'
import { UploadCloud, GitBranch, FileCheck2, AlertTriangle, CheckCircle2, Loader2, Sparkles } from 'lucide-react'
import { importGitHubRepository, seedPortfolio, uploadDocument } from '../lib/api'

export default function Upload(){
  const [file,setFile]=useState(null),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState('')
  const [github,setGithub]=useState('')
  const run=async action=>{setBusy(true);setError('');setResult(null);try{setResult(await action())}catch(e){setError(e.message)}finally{setBusy(false)}}
  const upload=()=>{if(!file)return setError('Choose a supported file first.');run(()=>uploadDocument(file,setProgress))}
  const importRepo=()=>{if(!github.trim())return setError('Enter a GitHub repository URL.');run(()=>importGitHubRepository(github.trim()))}
  return <div style={{padding:'32px 36px',maxWidth:1100,margin:'0 auto'}}>
    <div className="eyebrow"><Sparkles size={14}/> AI DATA INGESTION</div><h1 className="heading-display" style={{fontSize:'2rem',margin:'6px 0'}}>Add career evidence</h1><p style={{color:'#94a3b8',maxWidth:720,marginBottom:26}}>Files are fingerprinted, privately stored, split into page-aware evidence chunks, and connected to your career graph. Low-confidence fields are marked for review.</p>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:18}}>
      <section className="card" style={{padding:24}}><UploadCloud size={25}/><h2 style={{fontSize:17}}>Upload a document</h2><p style={{fontSize:13,color:'#64748b'}}>PDF, DOCX, PNG, JPG, JPEG, or WEBP · maximum 15 MB</p><label style={{display:'block',border:'1px dashed rgba(148,163,184,.35)',borderRadius:14,padding:28,textAlign:'center',cursor:'pointer',margin:'18px 0'}}><input type="file" accept=".pdf,.docx,.png,.jpg,.jpeg,.webp" hidden onChange={e=>{setFile(e.target.files?.[0]);setProgress(0)}}/><b>{file?.name||'Choose evidence file'}</b><div style={{fontSize:12,color:'#64748b',marginTop:5}}>Original format remains accessible through a private signed link.</div></label>{busy&&progress>0&&<div style={{height:7,background:'#1e293b',borderRadius:8,marginBottom:12}}><div style={{width:`${progress}%`,height:'100%',background:'#3b82f6',borderRadius:8}}/></div>}<button className="btn-primary" style={{width:'100%'}} disabled={busy} onClick={upload}>{busy?<Loader2 size={16} className="spin"/>:<FileCheck2 size={16}/>} Analyze and index</button></section>
      <section className="card" style={{padding:24}}><GitBranch size={25}/><h2 style={{fontSize:17}}>Import a GitHub project</h2><p style={{fontSize:13,color:'#64748b'}}>Adds source-linked project evidence from repository metadata, languages, topics, and README.</p><input value={github} onChange={e=>setGithub(e.target.value)} placeholder="https://github.com/owner/repository" style={{width:'100%',padding:'13px 14px',margin:'18px 0',borderRadius:10,border:'1px solid rgba(148,163,184,.2)',background:'rgba(15,23,42,.6)',color:'#e2e8f0'}}/><button className="btn-primary" style={{width:'100%'}} disabled={busy} onClick={importRepo}><GitBranch size={16}/> Import source-linked evidence</button><button onClick={()=>run(seedPortfolio)} disabled={busy} style={{width:'100%',marginTop:10,padding:11,borderRadius:10,border:'1px solid rgba(148,163,184,.15)',background:'transparent',color:'#94a3b8',cursor:'pointer'}}>Load hackathon demo journey</button></section>
    </div>
    {error&&<div className="card" style={{marginTop:18,padding:16,color:'#fca5a5',display:'flex',gap:10}}><AlertTriangle size={18}/>{error}</div>}
    {result&&<section className="card" style={{marginTop:18,padding:22}}><div style={{display:'flex',gap:10,alignItems:'center',color:'#34d399'}}><CheckCircle2 size={20}/><b>Evidence added successfully</b></div>{result.document&&<><h2 style={{fontSize:18,marginBottom:4}}>{result.document.title}</h2><div style={{fontSize:13,color:'#94a3b8'}}>{result.document.type} · confidence {Math.round((result.document.confidence||0)*100)}% · {result.document.verification_status}</div><p style={{color:'#cbd5e1'}}>{result.document.summary}</p></>}{result.processing&&<><div style={{fontSize:12,color:'#64748b'}}>Pages: {result.processing.page_count||1} · Evidence chunks: {result.processing.chunk_count||0}{result.processing.review_required?' · Metadata review required':''}</div>{result.processing.held_out_of_knowledge_graph&&<div style={{marginTop:14,padding:'12px 14px',borderRadius:11,display:'flex',gap:9,alignItems:'flex-start',color:'#fbbf24',background:'rgba(245,158,11,.10)',border:'1px solid rgba(245,158,11,.28)'}}><AlertTriangle size={17}/><div><b>Held out of semantic search and the knowledge graph</b><div style={{fontSize:12,color:'#d6a64d',marginTop:4,lineHeight:1.5}}>{result.processing.held_out_reason||'Confirm the highlighted metadata before this record can influence retrieval or career evidence.'}</div><div style={{fontSize:11,color:'#9a7b3e',marginTop:5}}>Integrity threshold: {Math.round((result.processing.review_confidence_threshold||0)*100)}%</div></div></div>}</>}{result.imported&&<div style={{fontSize:13,color:'#cbd5e1',marginTop:10}}>Imported {result.imported.length} demo documents; skipped {result.skipped?.length||0} duplicates.</div>}</section>}
  </div>
}
